# This is a basic workflow to help you get started with Actions

name: Bloodbowl blog CD

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: CI=true npm test
        shell: bash

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: 89.117.22.172
          username: "belmont"
          password: "belmont"
          port: 22
          script: |
            cd ~/bloodbowl-blog
            git pull origin main
            git status
            CI=true npm test
            CI=true npm run build
            npm run build